config/routes.rb
Rails.application.routes.draw do
  resources :mock_servers do
    resources :mocks do
      collection do
        get 'new' => 'mocks#new', as: 'new'
      end
      member do
        get '' => 'mocks#show'
        put '' => 'mocks#edit', as: 'edit'
      end
      collection do
        post '' => 'mocks#create'
        post 'when', to: :when, controller: 'mocks'
        get '*other'  => 'mocks#mock_get'
        post '*other'  => 'mocks#mock_post'
        put '*other'  => 'mocks#mock_put'
        delete '*other'  => 'mocks#mock_delete'
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mock.rb
class Mock < ApplicationRecord
  before_save :default_values
  def default_values
    self.body ||= "{}"
    self.query ||= "{}"
  end
end

app/models/mock_server.rb
class MockServer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/mock_servers_controller.rb
class MockServersController < ApplicationController
  before_action :set_mock_server, only: [:show, :edit, :update, :destroy]

  # GET /mock_servers
  # GET /mock_servers.json
  def index
    @mock_servers = MockServer.all
  end

  # GET /mock_servers/1
  # GET /mock_servers/1.json
  def show

  end


  # POST /mock_servers
  # POST /mock_servers.json
  def create
    @mock_server = MockServer.new(mock_server_params)

    respond_to do |format|
      if @mock_server.save
        format.json { render :show, status: :created, location: @mock_server }
      else
        format.json { render json: @mock_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mock_servers/1
  # PATCH/PUT /mock_servers/1.json
  def update
    respond_to do |format|
      if @mock_server.update(mock_server_params)
        format.html { redirect_to @mock_server, notice: 'Mock server was successfully updated.' }
        format.json { render :show, status: :ok, location: @mock_server }
      else
        format.html { render :edit }
        format.json { render json: @mock_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mock_servers/1
  # DELETE /mock_servers/1.json
  def destroy
    @mock_server.destroy
    respond_to do |format|
      format.html { redirect_to mock_servers_url, notice: 'Mock server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mock_server
      @mock_server = MockServer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mock_server_params
      params.require(:mock_server).permit(:name)
    end
end

app/controllers/mocks_controller.rb
class MocksController < ApplicationController
  include MockService
  include MockServersHelper::HttpMethods

  def show
    @mock = Mock.find(params[:id])
  end

  def index
    @mocks = Mock.where(mock_server_id: params["mock_server_id"])
    respond_to do |format|
      format.json { render json: @mocks }
    end
  end

  def new
    @mock = Mock.new(mock_server_id: params["mock_server_id"])
  end

  def create
    body = request.request_parameters
    mock_params = body.select {|key, value| ["url", "query", "method", "body", "result"].include? key }.merge(mock_server_id: params["mock_server_id"])
    mock = Mock.new(mock_params)
    mock.save
    redirect_to :action => :index, :mock_server_id => params[:mock_server_id]
  end

  def edit
    body = request.request_parameters
    updated_params = body.select {|key, value| ["url", "query", "method", "body", "result"].include? key }
    Mock.update(params[:id], updated_params)
    redirect_to :action => :index, :mock_server_id => params[:mock_server_id]
  end

  def delete

  end

  def when
    mock_server_id = params[:mock_server_id]
    mock = Mock.new(mock_params.merge(mock_server_id: mock_server_id))
    if mock.save
      respond_to do |format|
        format.json { render json: {'message': "mock saved successfully"} }
      end
    else
      respond_to do |format|
        format.json { render json: {'message': "something went wrong"} }
      end
    end
  end

  def mock_post
    get_result request
  end

  def mock_get
    get_result request
  end

  def mock_put
    get_result request
  end


  def mock_delete
    get_result request
  end

  private
  def get_result request
    url = params[:other]
    mock_server_id = params[:mock_server_id]
    body = request.request_parameters.except("mock")
    result = find_mocked_result(url, request.query_parameters, body, mock_server_id, request.method)
    render status: result[:status], json: result[:response]
  end


  def mock_params
    params.require(:mock).permit(:url, :body, :query, :result, :method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mock_servers_helper.rb
module MockServersHelper
  module HttpMethods
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mock_servers/_form.html.erb
<%= form_for(mock_server) do |f| %>
  <% if mock_server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mock_server.errors.count, "error") %> prohibited this mock_server from being saved:</h2>

      <ul>
      <% mock_server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mock_servers/edit.html.erb
<h1>Editing Mock Server</h1>

<%= render 'form', mock_server: @mock_server %>

<%= link_to 'Back', mock_servers_path %>

app/views/mock_servers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mock Servers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mock_servers.each do |mock_server| %>
      <tr>
        <td><%= link_to mock_server.name, mock_server_mocks_path(mock_server.id) %></td></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mock Server', new_mock_server_path %>

app/views/mock_servers/new.html.erb
<h1>New Mock Server</h1>

<%= render 'form', mock_server: @mock_server %>

<%= link_to 'Back', mock_servers_path %>

app/views/mock_servers/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
      <% @mocks.each do |mock| %>
        <tr>
          <td>URL</td>
          <td><%= mock.url %></td>
        </tr>
        <tr>
          <td>Method</td>
          <td><%= mock.method %></td>
        </tr>
        <tr>
          <td>Query</td>
          <td><%= mock.query %></td>
        </tr>
        <tr>
          <td>Body</td>
          <td><%= mock.body %></td>
        </tr>
        <tr>
          <td>Result</td>
          <td><%= mock.result %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<%= link_to 'Back', mock_servers_path %>

app/views/mocks/_form.html.erb
<%= form_tag(path, form_options) do %>
  <input type="text" name="url" value="<%= mock.url%>" placeholder="url to mock"/>
  <input type="text" name="method" value="<%= mock.method%>" placeholder="method"/>
  <input type="text" name="query" value="<%= mock.query%>" placeholder="query parameter as json"/>
  <input type="text" name="body" value="<%= mock.body%>" placeholder="body as json for post"/>
  <input type="text" name="result" value="<%= mock.result%>" placeholder="response as json"/>
  <%= submit_tag("Update") %>
<% end %>

app/views/mocks/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
  <% @mocks.each do |mock| %>
      <tr>
        <td>URL</td>
        <td><%= mock.url %></td>
        <td rowspan="5"><%= link_to 'Edit', mock_server_mock_path(mock_server_id: mock.mock_server_id, id: mock.id) %></td>
        <td rowspan="5"><%= link_to 'Delete' %></td>
      </tr>
      <tr>
        <td>Method</td>
        <td><%= mock.method %></td>
      </tr>
      <tr>
        <td>Query</td>
        <td><%= mock.query %></td>
      </tr>
      <tr>
        <td>Body</td>
        <td><%= mock.body %></td>
      </tr>
      <tr>
        <td>Result</td>
        <td><%= mock.result %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Back', mock_servers_path %>
<%= link_to 'New', new_mock_server_mocks_path %>

app/views/mocks/new.html.erb
<h1>New Mock Server</h1>

<%= render 'form', mock: @mock, path: mock_server_mocks_path, form_options: {method: "post"} %>

<%= link_to 'Back', mock_servers_path %>

app/views/mocks/show.html.erb
<h1>Editing Mock Server</h1>

<%= render 'form', mock: @mock, path: edit_mock_server_mock_path, form_options: {method: "put"}%>

<%= link_to 'Show', @mock_server %> |
<%= link_to 'Back', mock_servers_path %>